const years = {
  2000: {
    january: [
      {
        title: "hi",
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
    ],
    february: [
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
    ],
    march: [
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
    ],
  },
  2001: {
    january: [
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
    ],
    february: [
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
    ],
    march: [
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
      {
        title: null,
        date: null,
        location: null,
        theHindu: null,
        timesOfIndia: null,
        theIndianExpress: null,
        theHindustanTimes: null,
      },
    ],
  },
};
